### ISSUE TITLE
Installation problems in Ubuntu 16.10

### ISSUE THREAD

**Issue by fcabaud** [esa/opengeode#36]
- gnat-4.8

 sudo apt-get install gnat-4.8 
-> This package doesnt exist any more on Ubuntu 
I did  

> sudo apt-get install gnat-5

- libmono-corlib4.0-cil 
-> This package doesnt exist any more. 
I did
> sudo apt-get install libmono-corlib4.5-cil

- wget http://download.tuxfamily.org/taste/ASN1SCC/ASN1SCC-latest.tgz
> > sudo wget http://download.tuxfamily.org/taste/ASN1SCC/ASN1SCC-latest.tgz

- idem for tar 

> sudo zxvf ASN1SCC-latest.tgz

- sudo update-ca-certificate
-> **command not found**

**Comment by maxime-esa** [comment]
For `gnat`, any version will do, the more recent the better. I am using `gnat-6` on Debian Stretch.

Regarding `update-ca-certificate` I think you will not have any error if you clone the `gitlab` repo. The error happened on the ESA Gitlab repository, but even here I think it is fixed now.

Do you still have issues with the installation after doing the fixes you describe?

**Comment by fcabaud** [comment]
- well,

 with 

> sudo update-ca-certificates
It's OK

- make install
Trace is

Processing /home/fcabaud/opengeode
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-p3ok552i-build/setup.py", line 12, in <module>
        import opengeode
      File "/tmp/pip-p3ok552i-build/opengeode/__init__.py", line 28, in <module>
        from opengeode import opengeode, __version__, SDL_Scene, SDL_View, parse, init_qt
      File "/tmp/pip-p3ok552i-build/opengeode/opengeode.py", line 2409
        key=lambda (name, sort): name):
                   ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-p3ok552i-build/
Makefile:58 : la recette pour la cible « install » a échouée
make: *** [install] Erreur 1

> python version is Python 2.7.12+ (default, Sep 17 2016, 12:08:02)

**Comment by maxime-esa** [comment]
There is no syntax error, so I suspect that `pip` does not point to pip2 but to pip3 in your distro.
I updated the Makefile, can you run the following from the opengeode directory:

```
$ git pull
$ make full-install
```
This should properly install all dependencies. Then try to run the application with:

```
$ opengeode
```

**Comment by fcabaud** [comment]
-  sudo git pull
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Dépaquetage des objets: 100% (4/4), fait.
Depuis https://github.com/esa/opengeode
   3f6de43..1583a6a  master     -> origin/master
Mise à jour 3f6de43..1583a6a
Fast-forward
 Makefile          | 20 ++++++++++----------
 README.md         |  2 +-
 asn1-value-editor |  2 +-
 dmt               |  2 +-
 properties        |  2 +-
 pymsc             |  2 +-
 6 files changed, 15 insertions(+), 15 deletions(-)

- sudo make full-install
Chemin de sous-module 'asn1-value-editor' : '5652026598202a7c3230b4e322f7aa0b66377842' extrait
Chemin de sous-module 'dmt' : '6665e0632db0a1b11c2942bd8ae293a00d9bc126' extrait
Chemin de sous-module 'properties' : 'bfaa6f1858d7cc21a3daa8a52cb66339022e9e7c' extrait
Chemin de sous-module 'pymsc' : '291c7bcef7a6c4648e797103adeb42f4faf50a50' extrait
make: pip2 : commande introuvable
Makefile:47 : la recette pour la cible « dependencies » a échouée
make: *** [dependencies] Erreur 127

  -> pip2 wasn't installed (I dont known the difference with pip)

>  sudo apt install python-pip

- Then (again) sudo make full-install    
 from ply import yacc
    ImportError: No module named ply
->  sudo pip install ply
- Then (again) sudo make full-install    

Processing ./pygraphviz
Installing collected packages: pygraphviz
  Running setup.py install for pygraphviz ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-QSovEn-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-sMVYkv-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    /usr/lib/python2.7/dist-packages/setuptools/dist.py:364: UserWarning: Normalizing '1.4.dev' to '1.4.dev0'
      normalized_version,
    running install
    Trying pkg-config
    Package libcgraph was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libcgraph.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libcgraph' found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-QSovEn-build/setup.py", line 93, in <module>
        tests_require=['nose>=0.10.1', 'doctest-ignore-unicode>=0.1.0',],
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "setup_commands.py", line 44, in modified_run
        self.include_path, self.library_path = get_graphviz_dirs()
      File "setup_extra.py", line 121, in get_graphviz_dirs
        include_dirs, library_dirs = _pkg_config()
      File "setup_extra.py", line 44, in _pkg_config
        output = S.check_output(['pkg-config', '--libs-only-L', 'libcgraph'])
      File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['pkg-config', '--libs-only-L', 'libcgraph']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-QSovEn-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-sMVYkv-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-QSovEn-build/
Makefile:47 : la recette pour la cible « dependencies » a échouée
make: *** [dependencies] Erreur 1

**Comment by maxime-esa** [comment]
Make sure you have installed all dependencies indicated in the README, including `pkg-config`, `python-pyside`, `pyside-tools`, `graphviz`, `graphviz-dev`. `libgraphviz-dev`, `python-pip`.

I don't think you should use `sudo` to run the makefile and the pip installations.
The installation is done in the user space because pip is called with the `--user` flag.

**Comment by fcabaud** [comment]
Bingo
Installing collected packages: opengeode
  Running setup.py install for opengeode ... done
Successfully installed opengeode-1.5.28

Well, for running it. It's in 

>  ~/.local/bin/opengeode 

Thank so much

**Comment by maxime-esa** [comment]
Yep, you have to add ~/.local/bin to your PATH. 

Thanks for reporting these issues, the README and Makefile are better now.
