### ISSUE TITLE
Export PNG: neither background nor arrow

### ISSUE THREAD

**Issue by fcabaud** [esa/opengeode#38]
On Linux Ubuntu 16.10, when "I export To PNG", there is

- no background in the picture(white color would
 be appreciated) : remark : in this Web page, the background is white.
- no arrows except for the first status (called New here)

![fred](https://cloud.githubusercontent.com/assets/5073643/25069713/9d192a08-2289-11e7-8a22-a4d9ab2a982f.png)

**Comment by maxime-esa** [comment]
Acknowledged, the second point is a recent regression that was not spotted by the regression suite. Will look into it (also happening when you export from the command line)

Regarding the first point, the background is transparent on purpose, to give more flexibility.

**Comment by maxime-esa** [comment]
This is fixed in the latest commits

**Comment by maxime-esa** [comment]
Version 1.5.42 shipped in taste contains the fix. Closing
