### ISSUE TITLE
I can not install the pygraphviz!!!!!!!!!!

### ISSUE THREAD

**Issue by 289202471** [esa/opengeode#41]
the Error Info in my Pycharm:
![image](https://user-images.githubusercontent.com/29940173/53415132-5cf32280-3a0b-11e9-9a68-874b9a90464f.png)

**Comment by maxime-esa** [comment]
The installation procedure is meant for Linux. 

On Windows look for pre-build Windows package of Python modules (you will probably have the same issue with PySide and others). That's how I did the Windows binary built of opengeode (some years ago, I did not update it recently). Get all dependencies from there: https://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by 289202471** [comment]
> The installation procedure is meant for Linux.
> 
> On Windows look for pre-build Windows package of Python modules (you will probably have the same issue with PySide and others). That's how I did the Windows binary built of opengeode (some years ago, I did not update it recently). Get all dependencies from there: https://www.lfd.uci.edu/~gohlke/pythonlibs/

Thanks!!!!!
