### ISSUE TITLE
I can not open the example????

### ISSUE THREAD

**Issue by 289202471** [esa/opengeode#42]
Sorry to bother you again! But I can not open the example and I do not know the reason.

There are some errors ......

![image](https://user-images.githubusercontent.com/29940173/53538129-5c5fa680-3b47-11e9-8988-06dda79f65c7.png)

**Comment by 289202471** [comment]
the example is 
![123](https://user-images.githubusercontent.com/29940173/53538268-f0317280-3b47-11e9-8d46-c9d1c710b823.PNG)

**Comment by maxime-esa** [comment]
In this example you must open the two files at the same time (select both og.pr and system_structure.pr). They depend on each other.
Also: have you installed the ASN.1 Compiler (asn1scc) ?

**Comment by 289202471** [comment]
> In this example you must open the two files at the same time (select both og.pr and system_structure.pr). They depend on each other.
> Also: have you installed the ASN.1 Compiler (asn1scc) ?

What I used is the window binary build ,Do I still need the ASN.1 Compiler??? If I realy need ,How I get it???

**Comment by 289202471** [comment]
I select both og.pr and system_structure.pr,but then no use,and have no errors?????
![image](https://user-images.githubusercontent.com/29940173/53613782-21767500-3c12-11e9-99ea-3a9aa3f5b980.png)
No Errors and Nothing there!!!
![image](https://user-images.githubusercontent.com/29940173/53613815-41a63400-3c12-11e9-9eb0-206833fbe404.png)

**Comment by maxime-esa** [comment]
I checked the Windows binary and you do not need to install manually the ASN.1 compiler.

I can't reproduce the issue - on Windows the test1 opens properly with me. Do you have the same problem with other examples or is it only this one?

**Comment by 289202471** [comment]
> I checked the Windows binary and you do not need to install manually the ASN.1 compiler.
> 
> I can't reproduce the issue - on Windows the test1 opens properly with me. Do you have the same problem with other examples or is it only this one?

Thanks for your help !  I have the same problem with all the examples,and i do not know how to solve the problem.

**Comment by maxime-esa** [comment]
The issue is difficult to debug - the Windows build is old and not maintained. It could come from an incompatibility between your version of Windows and one of the Python dependencies (Qt4, Antlr, etc.). 

If that's an option for you I suggest to work on Linux which is the primary target platform for the tool. 

One more thing to check: after trying to open one of the examples on Windows, can you please close the tool and copy the content of the file named "opengeode_stderr.log", that is saved in the folder from which you ran Opengeode?

**Comment by 289202471** [comment]
> The issue is difficult to debug - the Windows build is old and not maintained. It could come from an incompatibility between your version of Windows and one of the Python dependencies (Qt4, Antlr, etc.).
> 
> If that's an option for you I suggest to work on Linux which is the primary target platform for the tool.
> 
> One more thing to check: after trying to open one of the examples on Windows, can you please close the tool and copy the content of the file named "opengeode_stderr.log", that is saved in the folder from which you ran Opengeode?

the content of the file named "opengeode_stderr.log"

**[INFO] Model backup enabled - auto-saving every 2 minutes
[ERROR] Aborting: could not open or parse input file**

**Comment by maxime-esa** [comment]
Oh, that's an IO error. Please copy also the content of opengeode_stdout.log

**Comment by 289202471** [comment]
> Oh, that's an IO error. Please copy also the content of opengeode_stdout.log

Maybe there is just an IO error.There is nothing in the opengeode_stdout.log

**Comment by 289202471** [comment]
> Can you try to unpack opengeode_windows.zip in c:>Temp\ and try to load the example files from there (i.e. without any long path)

Oh! Thanks! I can get the image . but there are some errors in the opengeode_stderr.log

**[INFO] Model backup enabled - auto-saving every 2 minutes
[ERROR] Cannot copy
[ERROR] Cannot copy
[ERROR] Cannot copy
[ERROR] Missing label: Then_What
[ERROR] Missing label: Then_What
[ERROR] Missing label: eight
[ERROR] Missing label: eight
Traceback (most recent call last):
  File "opengeode.py", line 2306, in upd_statechart
  File "Statechart.pyc", line 500, in render_statechart
  File "pygraphviz\agraph.pyc", line 1305, in layout
  File "pygraphviz\agraph.pyc", line 1251, in _run_prog
  File "pygraphviz\agraph.pyc", line 1239, in _get_prog
ValueError: Program neato not found in path.
[ERROR] Cannot copy
[ERROR] Cannot copy
[ERROR] Cannot copy**

**Comment by 289202471** [comment]
After I open the example ,There is a info shown to me!
![image](https://user-images.githubusercontent.com/29940173/53797582-70553f00-3f71-11e9-9de7-c68b60be6164.png)

**Comment by maxime-esa** [comment]
That's not errors of the program.

One thing: `neato not found`. This is a dependency (graphviz/dot) which is missing - used to transform the SDL model into statecharts. It is not packaged with opengeode, but this is probably something you can install manually from here: https://graphviz.gitlab.io/download/
This is not strictly needed to work with opengeode. It only gives a different (read-only) view of the diagram.

`Selection is incompatible with copy` means you did a Ctrl-C to copy something that cannot be copied. For example if you selected multiple items at once, you cannot copy/paste them in one go.
