### ISSUE TITLE
How to create a .asn file in openGeode???

### ISSUE THREAD

**Issue by 289202471** [esa/opengeode#44]
Sorry to bother you again! But I have a problem .
On the Taste offical website,There is a page 
http://taste.tuxfamily.org/wiki/index.php?title=Technical_topic:_OpenGEODE_-_Design_pattern:_How_to_emulate_the_SAVE_symbol   
I read it ,but i do not know how to create a data type
![image](https://user-images.githubusercontent.com/29940173/54109094-a5054280-4418-11e9-8c9e-4b88a79b781f.png)
I have tried to create the .asn file by myself at the .pr file path,and then open the .pr file at the OpenGEODE. But it no use????
 the file that i create by myself
![image](https://user-images.githubusercontent.com/29940173/54109460-aedb7580-4419-11e9-9908-7fc6ef3046c4.png)
![image](https://user-images.githubusercontent.com/29940173/54109529-ddf1e700-4419-11e9-9ef5-f1a90a578782.png)
but the OpenGEODE may not open it.
![image](https://user-images.githubusercontent.com/29940173/54109709-59539880-441a-11e9-9839-3df587a5f35b.png)
So Do you know How to create it by using OpenGEODE?

**Comment by maxime-esa** [comment]
To reference the ASN.1 file, you must create a text box and use this syntax:
![image](https://user-images.githubusercontent.com/1416005/54110237-3062e180-43e1-11e9-844f-12d375f4b354.png)

The name "dv" is random. Important is the comment 'file_name.asn'; part

**Comment by 289202471** [comment]
> To reference the ASN.1 file, you must create a text box and use this syntax:
> ![image](https://user-images.githubusercontent.com/1416005/54110237-3062e180-43e1-11e9-844f-12d375f4b354.png)
> 
> The name "dv" is random. Important is the `comment 'file_name.asn';` part

Ennnnnnn! Thanks, Do you have the example in the page ? I do not have that example.
![image](https://user-images.githubusercontent.com/29940173/54111331-93269e00-441e-11e9-9e22-aecf4a8c59f7.png)
If you have ,Could you please send that example to my email? Thanks!  My mail:289202471@nuaa.edu.cn

**Comment by maxime-esa** [comment]
All the test cases are in the git repository
This one is here: https://github.com/esa/opengeode/tree/master/tests/regression/test-save
