### ISSUE TITLE
I have a question about ASN

### ISSUE THREAD

**Issue by 289202471** [esa/opengeode#45]
Do you know how to use ASN syntax to represent long integers(Integer_64)?????

**Comment by maxime-esa** [comment]
`ASN.1` works with ranges, so if you specify a 64 bits range, that's what you will get:

```
T-Int64 ::= INTEGER (-9223372036854775808 .. 9223372036854775807)
```

It is better to work with your actual range need.When you generate code, ASN1SCC will use a 64bits integer anyway (or unsigned if you don't have negative values in your range)

**Comment by 289202471** [comment]
> `ASN.1` works with ranges, so if you specify a 64 bits range, that's what you will get:
> 
> ```
> T-Int64 ::= INTEGER (-9223372036854775808 .. 9223372036854775807)
> ```
> It is better to work with your actual range need.When you generate code, ASN1SCC will use a 64bits integer anyway (or unsigned if you don't have negative values in your range)

Ennnnn! How to represent float and double by ASN syntax?????

**Comment by maxime-esa** [comment]
I think you need to read an introduction to ASN.1. This one is the best: https://www.oss.com/asn1/resources/asn1-made-simple/introduction.html

**Comment by 289202471** [comment]
> I think you need to read an introduction to ASN.1. This one is the best: https://www.oss.com/asn1/resources/asn1-made-simple/introduction.html

Thanks for your help! Wish you a good mood every day!
