### ISSUE TITLE
Sorry , I am back again with a question

### ISSUE THREAD

**Issue by 289202471** [esa/opengeode#47]
How to express the infinity in asn.1????
I want to express the natural number by ASN.1

```
Natural::INTEGER(0..MAX);
```   
How to express this "MAX"?????

**Comment by maxime-esa** [comment]
Like this:
``` 
Natural ::= INTEGER (0 .. MAX)
```

Recommendation: to know _everything_ about ASN.1, dowload this book:
www.oss.com/asn1/resources/books-whitepapers-pubs/dubuisson-asn1-book.PDF
