### ISSUE TITLE
I want to ask something about the OpenGEODO

### ISSUE THREAD

**Issue by 289202471** [esa/opengeode#48]
I am reading the .pr file for the example called marco.
I want to ask what the meaning of this is.
![image](https://user-images.githubusercontent.com/29940173/56016441-d67e7000-5d2e-11e9-85f9-3eb0e0c8edd5.png)
the example is 
![image](https://user-images.githubusercontent.com/29940173/56016475-f01fb780-5d2e-11e9-9298-801889ce3338.png)

**Comment by maxime-esa** [comment]
It has no specific use at the moment, this was to  keep compatibility with another tool, to indicate that the external procedure is implemented in C.

**Comment by 289202471** [comment]
> It has no specific use at the moment, this was to keep compatibility with another tool, to indicate that the external procedure is implemented in C.

OK，thanks !

**Comment by 289202471** [comment]
en, another question in the .pr file
Still in that case.  I do not know the meaning of "FROM ENV TO marco WITH run_system;"
![image](https://user-images.githubusercontent.com/29940173/56017055-bea7eb80-5d30-11e9-81fb-2e10e87c0b5d.png)
I can not find something named “marco WITH run_system in the system”.
![image](https://user-images.githubusercontent.com/29940173/56017110-e13a0480-5d30-11e9-9e31-f9a173ebb06b.png)
In another case named og.pr. I can understand it becase in that case I can see it.
![image](https://user-images.githubusercontent.com/29940173/56017210-252d0980-5d31-11e9-8a64-3646a3bec3d5.png)
![image](https://user-images.githubusercontent.com/29940173/56017232-3a099d00-5d31-11e9-8ea2-fd19d30535f4.png)

**Comment by maxime-esa** [comment]
I don't understand. This is what I see:

![image](https://user-images.githubusercontent.com/1416005/56017523-d1ee9300-5cff-11e9-8570-7b3f97b48459.png)

When you opened marco.pr did you select it well together with system_structure.pr ?

Perhaps you had the other one open, and it mixed up the two system_structure.pr files. The Windows binary is old and not to date, so there could be a bug in that.

Try closing the tool and opening again demo1. You should see the right signals.

**Comment by 289202471** [comment]
> I don't understand. This is what I see:
> 
> ![image](https://user-images.githubusercontent.com/1416005/56017523-d1ee9300-5cff-11e9-8570-7b3f97b48459.png)
> 
> When you opened marco.pr did you select it well together with system_structure.pr ?
> 
> Perhaps you had the other one open, and it mixed up the two system_structure.pr files. The Windows binary is old and not to date, so there could be a bug in that.
> 
> Try closing the tool and opening again demo1. You should see the right signals.

Thanks ! Do you have some books about the grammer that the .pr file used. I want to learn about it.

**Comment by maxime-esa** [comment]
You have the complete standard here: https://www.itu.int/rec/T-REC-Z.100/

**Comment by 289202471** [comment]
> You have the complete standard here: https://www.itu.int/rec/T-REC-Z.100/

Really thanks! I get a great progress with your help!
