### ISSUE TITLE
A new question about openGEODE

### ISSUE THREAD

**Issue by 289202471** [esa/opengeode#50]
I want to define a datatype in dataview-uniq.asn
like this:
![image](https://user-images.githubusercontent.com/29940173/56774649-42b0a780-67f6-11e9-9b2f-288d74a0d54c.png)  
![image](https://user-images.githubusercontent.com/29940173/56774664-4f350000-67f6-11e9-93fb-d50977212a58.png)
but......
![image](https://user-images.githubusercontent.com/29940173/56774690-62e06680-67f6-11e9-9477-9f87ebf32941.png)

**Comment by maxime-esa** [comment]
In ASN.1 the fields of sequences must start with a lowercase letter. 
Types start with uppercase, but fields and enumerants start with lowercase.
