### ISSUE TITLE
Where can I get the defination of these procedures

### ISSUE THREAD

**Issue by 289202471** [esa/opengeode#52]
In the example /examples/demo1/marco.pr
![image](https://user-images.githubusercontent.com/29940173/57190210-8f108b80-6f4a-11e9-9d1b-952e46d1ee55.png)

**Comment by maxime-esa** [comment]
I believe that the examples in the windows bundled binary are partially incomplete. These procedures are declared external and the corresponding source code is not provided.
However that would be useful only to generate and integrate the code - which may not be very relevant on this example.

The windows binary of opengode is out of date and only the Linux version is maintained.
