### ISSUE TITLE
I meet another problem in Task!!!

### ISSUE THREAD

**Issue by 289202471** [esa/opengeode#53]
Sorry to bother you again.
![image](https://user-images.githubusercontent.com/29940173/61016301-c1fb5380-a3c1-11e9-94a4-22783901753f.png)
And, I also want to ask how to express "switch", "do-while" and "while" in the TASK in OpenGEODE.

**Comment by maxime-esa** [comment]
What you show in the screenshot can be done in SDL with a `DECISION` symbol:

![image](https://user-images.githubusercontent.com/1416005/61030937-c2deb600-a3be-11e9-80e9-0b6e963dcaf0.png)

Or using a ternary operator in a `TASK` symbol:

`someint := if someint > 0 then someint + 1 else someint - 1 fi`

The `DECISION` is also used for `switch-case`:

![image](https://user-images.githubusercontent.com/1416005/61031071-105b2300-a3bf-11e9-93a3-482db7125ee5.png)

And for ranges:

![image](https://user-images.githubusercontent.com/1416005/61031182-40a2c180-a3bf-11e9-9534-3795b8692e83.png)

Loops can be done either using decisions and label/join:

![image](https://user-images.githubusercontent.com/1416005/61031325-95ded300-a3bf-11e9-8ad7-751bad939149.png)

Or using the "for" construct in a `TASK` symbol (warning: this is an extension to SDL, it will not work in other tools). The syntax is close to Python loops, and there are two variants:

```
for each in range (10) :     // range operator has the same syntax as the one in Python
    call writeln(each);
endfor
``` 
and:
```  
for each in someArray : 
    // list of statements
endfor
```

**Comment by 289202471** [comment]
> Sorry to bother you again.
> ![image](https://user-images.githubusercontent.com/29940173/61016301-c1fb5380-a3c1-11e9-94a4-22783901753f.png)
> And, I also want to ask how to express "switch", "do-while" and "while" in the TASK in OpenGEODE.

Really thanks! A great help for me!
