### ISSUE TITLE
Multiple SDL Processes

### ISSUE THREAD

**Issue by SerenaC94** [esa/opengeode#57]
Hi,

I wanted to create a diagram containing two processes that communicate with each other (which is exactly what will happen in my implementation) but after I create one process in OpenGEODE the "Process" button becomes grayed out and I can only add "ProcessTypes".

Is it not possible to have multiple processes in OpenGEODE?

FYI, I have started studying SDL from this tutorial: https://www.sdl-forum.org/sdl88tutorial/index.html

**Comment by maxime-esa** [comment]
Opengeode iself can only handle one process at a time as it does not have the SDL communication view. That's what TASTE is actually providing.

TASTE provides the possibility to design a complete system made of one or more SDL processes, that can also communicate with other functions implemented in different languages (C, C++, Ada, Simulink, etc.) and generate complete code that can run on target (Linux or embedded).

Check www.opengeode.net for the subset of SDL that is supported by Opengeode

**Comment by SerenaC94** [comment]
Perfect, thank you.
