### ISSUE TITLE
Could you please give me a user manual about the opengeode?

### ISSUE THREAD

**Issue by yiji-kong** [esa/opengeode#60]
I hope to extend the OpenGeode,  and I needs some help about the source code of the tool. I can not find enough information in the README. Thanks a lot.

**Comment by maxime-esa** [comment]
Most of the documentation is embedded in the code itself.
What kind of extensions are you planning to do ? I can probably help you start and give you the right pointers.
Make sure you work in the branch named `python3-pyside2`, this is the active one at the moment. Master branch is still based on Python2 and Pyside1 which are not supported anymore, so in the short term this branch will disappear.

**Comment by nuaaysh** [comment]
In fact, we @yiji-kong  are developing a multi-task code generation tool for SDL by using OpenGenode. @maxime-esa Thanks for your suggestions. We find there are a lot of comments in the code.

**Comment by maxime-esa** [comment]
Sounds great. Let me know if you need help. Note that I recently merged the code from the python3-pyside2 branch into master. Make sure you fork from this point, as the Python2 code is not going to be further maintained.

**Comment by nuaaysh** [comment]
Thanks for your notification, you're very kind!

**Comment by wbnns** [comment]
@yiji-kong @nuaaysh 

Hi! :) Not sure where you are on your project these days, but in case helpful and you hadn't seen it already, there's also a [wiki for OpenGEODE](https://taste.tuxfamily.org/wiki/index.php?title=Technical_topic:_OpenGEODE,_an_SDL_editor_for_TASTE) with lots of info.

**Comment by nuaaysh** [comment]
> @yiji-kong @nuaaysh
> 
> Hi! :) Not sure where you are on your project these days, but in case helpful and you hadn't seen it already, there's also a [wiki for OpenGEODE](https://taste.tuxfamily.org/wiki/index.php?title=Technical_topic:_OpenGEODE,_an_SDL_editor_for_TASTE) with lots of info.

Hi,
      Thanks a lot, we had seen the wiki page. 
      Currently, @yiji-kong  are working on this work, I'm working on another topic.
Best wishes,

**Comment by maxime-esa** [comment]
For info, I added a new page to the wiki with a more detailed tutorial on SDL and Opengeode, here: https://taste.tuxfamily.org/wiki/index.php?title=Detailed_SDL_tutorial
