### ISSUE TITLE
Combining the READMEs

### ISSUE THREAD

**Issue by wbnns** [esa/opengeode#66]
I noticed there are two READMEs[1][2] in the repository. In case helpful, happy to take a stab at combining them, or can adhere to guidelines for how they should be synthesized.

[1] https://github.com/esa/opengeode/blob/master/README
[2] https://github.com/esa/opengeode/blob/master/README.md

**Comment by maxime-esa** [comment]
I think the non-md one can be removed. No point in keeping them both - The md one does not contain a lot of formatting anyway.
