### ISSUE TITLE
Website for OpenGEODE

### ISSUE THREAD

**Issue by wbnns** [esa/opengeode#71]
If at some point it might be helpful to have a website about OpenGEODE, I'd be happy to take a shot at putting one together.

**Comment by maxime-esa** [comment]
Thanks for offering

It's arguably limited, but there is www.opengeode.net

There is definitely room for improvement.. Any ideas and contributions are more than welcome!

**Comment by wbnns** [comment]
Thanks for the link! What's the preferred way to contribute?

**Comment by maxime-esa** [comment]
The best is to write .md files in a folder of OG (add "wiki" or inside "doc") and make pull requests there. I'll merge them in the taste wiki, but they will remain maintained in the main repo.
