### ISSUE TITLE
Having trouble getting started with OpenGEODE via TASTE VM

### ISSUE THREAD

**Issue by wbnns** [esa/opengeode#74]
I've installed OpenGEODE via the Taste VM, however, I'm having trouble accessing it when following the TASTE Quick Reference. Not sure if there is an example project I can quickly access to begin playing around with OpenGEODE to be able to see how it fits together with this repository? Or if there are a set of steps I can follow to quickly create one?

Not sure if this is the right place for this issue; apologies if not. :)

**Comment by maxime-esa** [comment]
The current TASTE VM is a bit old - it is based on Debian9 which does not have important dependencies to support the latest version of OpenGEODE - it is missing Python3.7+ and PySide2. We are working on the updgrade, but it's not ready yet.

If you are familiar enough with Linux, you can manually upgrade:
Set Debian10 repos to /etc/apt/sources.list: add `deb http://ftp.fr.debian.org/debian/ buster main non-free contrib` and run `sudo apt update` / `sudo apt upgrade`

Then go to the `~/tool-src` folder and run
```
$ git pull
$ git checkout feature_buster
$ ./Update-TASTE.sh
```

This should hopefully upgrade everything. It's an alpha-release, so expect some glitches here and there, but overall it is quite stable.

After this upgrade, you can work wit the latest version of the tools, in particular the new Kazoo build system and Opengeode 3.xx (which you can update at any time). The Quick Reference Card has not been updated to reflect this yet.

The main differences to create/edit a project is that you must just run `taste` (and **not** `taste-create-project`/`taste-edit-project` anymore).  To build, run `make`.

You can check an example of a system using Opengeode if you go in `~/tool-src/kazoo/tests/Demo_ABB_Opengeode` and run `make` to build it. Then `taste` to edit.

**Comment by wbnns** [comment]
Thanks for spending the time to detail this and help me understand. I will give this a try and report back.

**Comment by wbnns** [comment]
@maxime-esa 

Success! :) Thanks again!

<img width="2518" alt="image" src="https://user-images.githubusercontent.com/1130872/86512685-c8b18080-bdf3-11ea-9014-9f3cc516a451.png">

Below is a summary of steps I took in the TASTE VM based on your guidance above, to get it up to date.

***

*Enter shell in TASTE VM:*
```
# Switch to root
sudo su

# Make sure VM image is up to date
apt-get update
apt-get upgrade
apt-get dist-upgrade

# Point APT to Buster to prepare for upgrade
sed -i 's/stretch/buster/g' /etc/apt/sources.list

# Upgrade packages to Buster; when prompted allow services to be restarted automatically
apt-get upgrade

# Upgrade distribution to Buster
apt-get dist-upgrade

# Remove packages no longer needed
apt-get autoremove

# Return to taste user; exit root
exit

# Navigate to TASTE source; upgrade
cd ~/tool-src
git pull
git checkout feature_buster
./Update-TASTE.sh

# Make OpenGEODE demo
cd ~/tool-src/kazoo/tests/Demo_ABB_Opengeode
make
taste
```
Notes:
+ I was using bash, so I also ran `cd /bin ; sudo rm sh ; sudo ln -s bash sh` when prompted.
+ It seems post-upgrade that there are now multiple versions of RTEMS referenced in `~/.bashrc.taste`

* * *

Would you like me to add a few notes to `README.md` under the  **Installation** section about upgrading the TASTE VM, in case other people go that route as opposed to the manual installation?

**Comment by maxime-esa** [comment]
Yes, that's a good idea until we upgrade the TASTE VM to Debian 10 (work is ongoing, but it takes some time!). Thanks!

**Comment by wbnns** [comment]
Cheers, ok, will do!
