### ISSUE TITLE
PyPI opengeode project

### ISSUE THREAD

**Issue by BotellaA** [esa/opengeode#78]
I was looking at your project page on PyPI (https://pypi.org/project/opengeode/) and I was wondering if it was still alive. It has not been updated for 4 years.

I am asking this because I also have a project called "opengeode" that I would like to publish on PyPI. Before finding a workaround name for my project, I wanted to contact you to make sure your PyPI project was still used.

Thanks for your answer

**Comment by maxime-esa** [comment]
Dear Arnaud, yes Opengeode is active as you can see from the commits in this repo.

I have not updated the Python2 version of pypi lately as the project was just upgraded to Python3 and I did not have time to make the Python3 version available via pip. I will shortly. Sorry for that name conflict. I did not think the name opengeode would ever be used by another project :-)

**Comment by BotellaA** [comment]
Thanks @maxime-esa for your answer. I will look for another name for the pypi project.
