### ISSUE TITLE
Generated Ada code is wrong for decision with grouped answers

### ISSUE THREAD

**Issue by Glamhoth** [esa/opengeode#87]
Given a decision with its answers grouped
![image](https://user-images.githubusercontent.com/5027115/193844679-ff17c329-9dfc-4d6e-ac33-a4b95b668529.png)

then generated Ada code contains a syntax error in the `if` statement
![image](https://user-images.githubusercontent.com/5027115/193844863-089d77b1-f113-4c71-84f4-861f1499f97e.png)

**Comment by Glamhoth** [comment]
Simple case for reproducing
[grouped_answers.zip](https://github.com/esa/opengeode/files/9707985/grouped_answers.zip)
```
opengeode --toAda system_structure.pr ponger.pr
asn1scc -Ada --type-prefix asn1Scc -equal dataview-uniq.asn ponger_datamodel.asn
gcc -c ponger.adb
```
got: `ponger.adb:37:21: missing operand`

**Comment by maxime-esa** [comment]
fixed
